# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: AMS ADDON
version: "1.2.0"
slug: ams
description: AMS ADDON!
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  # - armhf
  # - armv7
  # - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw
host_network: true
options:
  local_addr: ""
  remote_addr: ""
  token: ""
schema:
  local_addr: str
  remote_addr: str
  token: str

