# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.3.3
  amd64: ghcr.io/hassio-addons/debian-base:7.3.3
  # armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  # armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  # i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: EMS add-on"
  org.opencontainers.image.description: "EMS a simple way to make your home assistant public."
  org.opencontainers.image.source: "https://github.com/bitfox-git/ems-ha"
  org.opencontainers.image.licenses: "Apache License 2.0"
