# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: EMS ADDON
version: "0.1.0"
slug: ems
description: EMS Home Assistant Addon
url: "https://github.com/bitfox-git/ems-ha"
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw
  - homeassistant_config:rw
  - backup:rw
host_network: true
options:
  local_addr: ""
  remote_addr: ""
  token: ""
  name: ""
schema:
  local_addr: str
  remote_addr: str
  token: str
  name: str
